server {
    listen 80;
    listen [::]:80;
    server_name saju.link www.saju.link;

    root /var/www/saju.link;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
